# Generated by Django 3.0.6 on 2020-07-19 14:21

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=smartfields.fields.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
